# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work_leave.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='work_leave.proto',
  package='work_leave',
  syntax='proto3',
  serialized_pb=_b('\n\x10work_leave.proto\x12\nwork_leave\"g\n\x08\x45mployee\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63\x63rued_leave_days\x18\x03 \x01(\x02\x12\x1c\n\x14requested_leave_days\x18\x04 \x01(\x02\"$\n\x10LeaveEligibility\x12\x10\n\x08\x65ligible\x18\x01 \x01(\x08\"X\n\rLeaveFeedback\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x1a\n\x12\x61\x63\x63rued_leave_days\x18\x02 \x01(\x02\x12\x1a\n\x12granted_leave_days\x18\x03 \x01(\x02\x32\xa1\x01\n\x18\x45mployeeLeaveDaysService\x12\x46\n\x10\x45ligibleForLeave\x12\x14.work_leave.Employee\x1a\x1c.work_leave.LeaveEligibility\x12=\n\ngrantLeave\x12\x14.work_leave.Employee\x1a\x19.work_leave.LeaveFeedbackb\x06proto3')
)




_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='work_leave.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='employee_id', full_name='work_leave.Employee.employee_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='work_leave.Employee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accrued_leave_days', full_name='work_leave.Employee.accrued_leave_days', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requested_leave_days', full_name='work_leave.Employee.requested_leave_days', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=135,
)


_LEAVEELIGIBILITY = _descriptor.Descriptor(
  name='LeaveEligibility',
  full_name='work_leave.LeaveEligibility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eligible', full_name='work_leave.LeaveEligibility.eligible', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=173,
)


_LEAVEFEEDBACK = _descriptor.Descriptor(
  name='LeaveFeedback',
  full_name='work_leave.LeaveFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='granted', full_name='work_leave.LeaveFeedback.granted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accrued_leave_days', full_name='work_leave.LeaveFeedback.accrued_leave_days', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_leave_days', full_name='work_leave.LeaveFeedback.granted_leave_days', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['LeaveEligibility'] = _LEAVEELIGIBILITY
DESCRIPTOR.message_types_by_name['LeaveFeedback'] = _LEAVEFEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'work_leave_pb2'
  # @@protoc_insertion_point(class_scope:work_leave.Employee)
  ))
_sym_db.RegisterMessage(Employee)

LeaveEligibility = _reflection.GeneratedProtocolMessageType('LeaveEligibility', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEELIGIBILITY,
  __module__ = 'work_leave_pb2'
  # @@protoc_insertion_point(class_scope:work_leave.LeaveEligibility)
  ))
_sym_db.RegisterMessage(LeaveEligibility)

LeaveFeedback = _reflection.GeneratedProtocolMessageType('LeaveFeedback', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEFEEDBACK,
  __module__ = 'work_leave_pb2'
  # @@protoc_insertion_point(class_scope:work_leave.LeaveFeedback)
  ))
_sym_db.RegisterMessage(LeaveFeedback)



_EMPLOYEELEAVEDAYSSERVICE = _descriptor.ServiceDescriptor(
  name='EmployeeLeaveDaysService',
  full_name='work_leave.EmployeeLeaveDaysService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=266,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='EligibleForLeave',
    full_name='work_leave.EmployeeLeaveDaysService.EligibleForLeave',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEE,
    output_type=_LEAVEELIGIBILITY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='grantLeave',
    full_name='work_leave.EmployeeLeaveDaysService.grantLeave',
    index=1,
    containing_service=None,
    input_type=_EMPLOYEE,
    output_type=_LEAVEFEEDBACK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMPLOYEELEAVEDAYSSERVICE)

DESCRIPTOR.services_by_name['EmployeeLeaveDaysService'] = _EMPLOYEELEAVEDAYSSERVICE

# @@protoc_insertion_point(module_scope)
